apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: termix
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: termix
  source:
    repoURL: 'https://github.com/Tapeline/exp-homelab-gitops.git'
    path: config/services/termix
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
