apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: hmac_secret
      remoteRef:
        key: kv-main/authelia
        property: hmac_secret
    - secretKey: jwk_private
      remoteRef:
        key: kv-main/authelia
        property: jwk_private
    - secretKey: jwt_secret
      remoteRef:
        key: kv-main/authelia
        property: jwt_secret
    - secretKey: storage_enc
      remoteRef:
        key: kv-main/authelia
        property: storage_enc

    - secretKey: termix_hash
      remoteRef:
        key: kv-main/oidc/termix
        property: hash
    - secretKey: tuwunel_hash
      remoteRef:
        key: kv-main/oidc/tuwunel
        property: hash
